### ISSUE TITLE
Name resolution problem since 0.97.2

### ISSUE THREAD

**Issue by wneessen** [home-assistant/hassio#1231]
**Home Assistant release with the issue:**
0.97.2

**Operating environment (HassOS/Generic):**
HASS.io running on Raspberry PI 3B
```
arch: armv7
channel: stable
hassos: null
homeassistant: 0.97.2
hostname: null
logging: info
machine: raspberrypi3
supervisor: "179"
supported_arch:
- armv7
- armhf
timezone: Europe/Berlin
```

**Supervisor logs:**
19-08-16 20:38:15 INFO (MainThread) [__main__] Initialize Hass.io setup
19-08-16 20:38:15 INFO (SyncWorker_0) [hassio.docker.supervisor] Attach to Supervisor homeassistant/armhf-hassio-supervisor with version 179
19-08-16 20:38:15 INFO (SyncWorker_0) [hassio.docker.supervisor] Connect Supervisor to Hass.io Network
19-08-16 20:38:17 INFO (SyncWorker_0) [hassio.docker.interface] Cleanup images: ['homeassistant/armhf-hassio-supervisor:178']
19-08-16 20:38:18 INFO (MainThread) [__main__] Setup HassIO
19-08-16 20:38:18 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/armhf-hassio-dns with version 1
19-08-16 20:38:18 INFO (MainThread) [hassio.dns] Update resolv from Supervisor
19-08-16 20:38:18 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.systemd1 on /org/freedesktop/systemd1
19-08-16 20:38:18 INFO (MainThread) [hassio.misc.forwarder] Start DNS port forwarding to 172.30.32.3
19-08-16 20:38:18 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error connecting: Could not connect: No such file or directory\n'
19-08-16 20:38:18 WARNING (MainThread) [hassio.dbus.systemd] Can't connect to systemd
19-08-16 20:38:18 INFO (MainThread) [hassio.utils.gdbus] Introspect org.freedesktop.hostname1 on /org/freedesktop/hostname1
19-08-16 20:38:18 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error connecting: Could not connect: No such file or directory\n'
19-08-16 20:38:18 WARNING (MainThread) [hassio.dbus.hostname] Can't connect to hostname
19-08-16 20:38:18 INFO (MainThread) [hassio.utils.gdbus] Introspect de.pengutronix.rauc on /
19-08-16 20:38:18 ERROR (MainThread) [hassio.utils.gdbus] DBus return error: b'Error connecting: Could not connect: No such file or directory\n'
19-08-16 20:38:18 WARNING (MainThread) [hassio.dbus.rauc] Can't connect to rauc
19-08-16 20:38:18 INFO (MainThread) [hassio.host.apparmor] Load AppArmor Profiles: {'hassio-supervisor'}
19-08-16 20:38:18 INFO (MainThread) [hassio.host.apparmor] AppArmor is not enabled on host
19-08-16 20:38:18 INFO (SyncWorker_2) [hassio.docker.interface] Attach to homeassistant/raspberrypi3-homeassistant with version 0.97.2
19-08-16 20:38:19 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/cebe7a76 repository
19-08-16 20:38:19 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/git/a0d7b954 repository
19-08-16 20:38:19 INFO (MainThread) [hassio.store.git] Load add-on /data/addons/core repository
19-08-16 20:38:20 INFO (MainThread) [hassio.store] Load add-ons from store: 60 all - 60 new - 0 remove
19-08-16 20:38:20 INFO (MainThread) [hassio.addons] Found 10 installed add-ons
19-08-16 20:38:20 INFO (SyncWorker_5) [hassio.docker.interface] Attach to homeassistant/armv7-addon-ssh with version 6.2
19-08-16 20:38:20 INFO (SyncWorker_6) [hassio.docker.interface] Attach to hassioaddons/grafana-armv7 with version v2.2.3
19-08-16 20:38:20 INFO (SyncWorker_0) [hassio.docker.interface] Attach to sabeechen/hassio-google-drive-backup-armv7 with version 0.98.2
19-08-16 20:38:20 INFO (SyncWorker_13) [hassio.docker.interface] Attach to hassioaddons/influxdb-armv7 with version v3.1.2
19-08-16 20:38:20 INFO (SyncWorker_8) [hassio.docker.interface] Attach to homeassistant/armv7-addon-mosquitto with version 5.0
19-08-16 20:38:20 INFO (SyncWorker_7) [hassio.docker.interface] Attach to homeassistant/armv7-addon-duckdns with version 1.9
19-08-16 20:38:20 INFO (SyncWorker_3) [hassio.docker.interface] Attach to homeassistant/armv7-addon-git_pull with version 7.4
19-08-16 20:38:20 INFO (SyncWorker_0) [hassio.docker.interface] Attach to homeassistant/armhf-addon-bluetooth_bcm43xx with version 2.3
19-08-16 20:38:20 INFO (SyncWorker_10) [hassio.docker.interface] Attach to homeassistant/armv7-addon-check_config with version 2.2
19-08-16 20:38:20 INFO (SyncWorker_5) [hassio.docker.interface] Attach to homeassistant/armhf-addon-deconz with version 3.1
19-08-16 20:38:20 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-08-16 20:38:20 INFO (MainThread) [hassio.snapshots] Found 10 snapshot files
19-08-16 20:38:20 INFO (MainThread) [hassio.discovery] Load 2 messages
19-08-16 20:38:20 INFO (MainThread) [hassio.ingress] Load 2 ingress session
19-08-16 20:38:20 INFO (MainThread) [__main__] Run Hass.io
19-08-16 20:38:20 INFO (MainThread) [hassio.api] Start API on 172.30.32.2
19-08-16 20:38:20 INFO (MainThread) [hassio.addons] Phase 'initialize' start 1 add-ons
19-08-16 20:38:21 INFO (SyncWorker_19) [hassio.docker.interface] Clean addon_core_bluetooth_bcm43xx application
19-08-16 20:38:29 INFO (SyncWorker_19) [hassio.docker.addon] Start Docker add-on homeassistant/armhf-addon-bluetooth_bcm43xx with version 2.3
19-08-16 20:38:30 INFO (MainThread) [hassio.homeassistant] Updated Home Assistant API token
19-08-16 20:38:34 INFO (MainThread) [hassio.core] Hass.io reboot detected
19-08-16 20:38:34 INFO (MainThread) [hassio.tasks] All core tasks are scheduled
19-08-16 20:38:34 INFO (MainThread) [hassio.core] Hass.io is up and running
19-08-16 20:38:58 INFO (MainThread) [hassio.api.security] /homeassistant/restart access from core_ssh
19-08-16 20:38:58 INFO (SyncWorker_13) [hassio.docker.interface] Restart homeassistant/raspberrypi3-homeassistant
19-08-16 20:39:00 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-08-16 20:39:00 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
19-08-16 20:39:26 ERROR (MainThread) [hassio.homeassistant] Error on call https://172.30.32.1:8123/api/states/binary_sensor.snapshots_stale: Cannot connect to host 172.30.32.1:8123 ssl:None [Connection refused]
19-08-16 20:39:26 ERROR (MainThread) [hassio.api.proxy] Error on API for request states/binary_sensor.snapshots_stale
19-08-16 20:39:46 INFO (MainThread) [hassio.homeassistant] Detect a running Home Assistant instance
19-08-16 20:40:15 INFO (MainThread) [hassio.api.security] /dns/logs access from core_ssh
19-08-16 20:41:17 INFO (MainThread) [hassio.api.security] /supervisor/logs access from core_ssh

**Description of problem:**
See this thread in the forum: https://community.home-assistant.io/t/name-resolution-problem-since-0-97-2/132201

Looks like several people have issues with the HASS internal DNS system. Even after updating the DNS server to my local router, the internal name resolution in HASS still fails.

```
hassio dns options --servers dns://192.168.178.1
````

```
ERROR (MainThread) [homeassistant.components.mjpeg.camera] Error getting new camera image: Cannot connect to host archpi.fritz.box:8081 ssl:None [Name does not resolve]
````

**Comment by DeviousPenguin** [comment]
I'm having this issue also, you may need to reboot the entire machine for the DNS changes to take effect.

You may be able to do it by just restarting the `hassio_dns` container, but I didn't want to experiement too much, I just wanted a working system.

**Comment by thrawnarn** [comment]
Most of my DNS-problems has been solved by setting the DNS-server to my local and rebooting but not all. For some reason some of my services still isn’t accessible from Home Assistant

**Comment by agners** [comment]
Just restarting `hassio_dns` was not enough for me, I had to restart the entire box. But I think since then things resolve as normal again.

**Comment by agners** [comment]
That was too soon. It seems to resolve about 50% of the time. As if there is yet another forwarder which is not shown in `hassio dns info`...

**Comment by agners** [comment]
Just used Wireguard to monitor what CoreDNS is exactly doing. It indeed still uses 1.1.1.1 and 8.8.8.8 besides my internal server. This is although only the internal DNS is set... This is very uncool.

**Comment by thrawnarn** [comment]
Thats good information, then it is possible to redirect all those requests in the firewall to the internal DNS-server. Maybe not a solution for everyone, but it works for me. Thanks!

**Comment by agners** [comment]
I guess this is the line which causes the issue:
https://github.com/home-assistant/hassio/blob/master/hassio/dns.py#L212

Hassio always adds the statically configured DNS_SERVERS. This is defined in const.py as `DNS_SERVERS = ["dns://8.8.8.8", "dns://1.1.1.1"]`

**Comment by agners** [comment]
Editing `hassio/dns/corefile` manually, deleting the superfluous servers and restart using `docker restart hassio_dns` solves the issue here, at least for now.

**Comment by bdf0506** [comment]
> Editing `hassio/dns/corefile` manually, deleting the superfluous servers and restart using `docker restart hassio_dns` solves the issue here, at least for now.

I don't think this works. Upon reboot of the host, this gets cleared back to the defaults.

/opt/hassio/dns.json:
`{
  "servers": [
    "dns://8.8.8.8",
    "dns://1.1.1.1"
  ],
  "version": "1"`

/opt/hassio/dns/corefile:
`.:53 {
    log
    hosts /config/hosts {
        fallthrough
    }
    forward . dns://8.8.8.8 dns://1.1.1.1 {
        health_check 10s
    }
}`

Unless there is somewhere else where this can be set so this doesnt happen?

**Comment by startrk1995** [comment]
Ugh.  Please put this back.  It is breaking my PiHole/local dns.

**Comment by agners** [comment]
Yeah I assumed that it will be overwritten, its more meant as a temporary a work around. I hope that this gets fixed rather soon.

**Comment by robby-dermody** [comment]
This change seems to have totally broke my home assistant install as well. I am using an internal DNS server, and block outbound access to public DNS servers (such as 8.8.8.8). I would need hass.io to use _only_ the internal DNS server.

**Comment by hgregorian** [comment]
+1 This is awful.  I just came across this issue after spending the better part of the last few hours troubleshooting every level of my infrastructure.  Please fix / revert.  Supplying internal DNS via `hassio dns` and then rebooting the node does not result in a fix and DNS resolution is intermittent at best.

**Comment by NearlCrews** [comment]
This just nuked the majority of my local devices connected to Home Assistant. It will not resolve anything using a local DNS name, e.g. nodemcu.mynetwork.local. I understand mistakes happen, but this was a horrible idea and implementation.

**Comment by NearlCrews** [comment]
FYI for those running Hass.IO on Ubuntu:

`vi /usr/share/hassio/dns/corefile`

Change the DNS entries in there. Then do:

`docker restart hassio_dns`

And then restart HA from the UI. It should come back but will likely be overwritten if the container updates without this being corrected. Thanks to the instructions above for the pointer.

**Comment by boojew** [comment]
I don't understand this change. How is it that hass.io believes that it must mandate its own resolver in this manner?

**Comment by nickrout** [comment]
7 hours on a major breakage and no developers?

**Comment by alexyao2015** [comment]
Seriously I spent several hours trying to figure out what happened. I never even updated hassio and still somehow got the update. Please fix this.

**Comment by wneessen** [comment]
> 7 hours on a major breakage and no developers?

Be fair. This is an open source project and most users will probably not even notice this change. This might be a "major breakdown" for you, but not generally for the whole HA community. It's a friday night... give them a chance to look at it. I mean in the end you can still revert to an older snapshot (if you have one). You probably got lots of great shit from this project - for free... that also brings with it, that you don't have a "3 business hours support" contract. I'm pretty sure, the fact that this has 18 comments already will point the DEVs to this bug and that there will be a fix soon. Just don't expect it in like 5 minutes after an issue is filed.

**Comment by DrMarlin** [comment]
What a mess - I wasted hours trying to figure out what was wrong, all of my DNS was broken. 

I attempted recovering via SSH and manually downgraded the supervisor with the following commands:

hassio supervisor update --version=173

This downgrades supervisor to a version from last week.

Unfortunately, it just re-updates to 179 upon reboot.

Trying to figure out how to block it from updating for the time being.

**Comment by alexyao2015** [comment]
Looks like #1230 and #1232 are also about this same issue.

**Comment by frenck** [comment]
You can set a custom dns server using `hassio dns options --server dns://IP_ADDRESS`
The bug right now, it doesn't process that request properly, as a work around a system reboot force the update of the DNS. We are looking into fixing this asap.

**Comment by mihalski** [comment]
For anyone who doesn't figure it out, it's `--servers`.

**Comment by NearlCrews** [comment]
@frenck what's the best way to approach this if you're running [Hass.io on Ubuntu](https://github.com/home-assistant/hassio-installer)? I've been running it that way for a while and never had an issue with DNS until this. There doesn't appear to be a `hassio` command in that type of environment.

**Comment by nhorvath** [comment]
> You can set a custom DNS server using `hassio dns options --server dns://IP_ADDRESS`
> The bug right now, it doesn't process that request properly, as a workaround a system reboot force the update of the DNS. We are looking into fixing this asap.
> 
> And please stop editing generated files manually, that is just bad practice and really not needed.

But why is it ignoring dns servers pushed by DHCP in the first place?

**Comment by nhorvath** [comment]
I tried using the command to set dns to my local dns and did hassio host reboot but it still does not resolve in containers.

**Comment by frenck** [comment]
@NearlCrews 
> I get your comment about not manually editing configuration files, but it's not like there's a ton of documentation on this or how to correct the issue, especially for the generic host installs. The change was to get it up and running again until the issue is fixed and we've got instructions to make it permanent.

The Hass.io CLI is available in the SSH, SSH & Web Terminal, Visual Studio Code and IDE add-ons.

**Comment by NearlCrews** [comment]
@frenck 

Ha, I somehow never noticed the option for a terminal in VSS. Thanks.

**Comment by alexyao2015** [comment]
@frenck 
I just tried that in VS Code and am getting an error.

```
➜  /config hassio dns options --server dns://10.0.0.10
Error: unknown command "dns" for "hassio"
Run 'hassio --help' for usage.
FATA[0000] Error while executing rootCmd: unknown command "dns" for "hassio" 

```

**Comment by nhorvath** [comment]
> @frenck
> I just tried that in VS Code and am getting an error.
> 
> ```
> ➜  /config hassio dns options --server dns://10.0.0.10
> Error: unknown command "dns" for "hassio"
> Run 'hassio --help' for usage.
> FATA[0000] Error while executing rootCmd: unknown command "dns" for "hassio" 
> ```

It's --servers

**Comment by alexyao2015** [comment]
Yeah just realized that. Same error through.

**Comment by mikemoyse** [comment]
hassio dns options --servers dns://IP_ADDRESS doesn't work for me. I installed DNSMASQ as I hoped this would work around it but that is ignored as well. Many broken things right now and reverting to an older version with a working supervisor just gets updated again. Give me back control of my system! :-)

**Comment by nhorvath** [comment]
what commands show available on hassio help?

**Comment by alexyao2015** [comment]
➜  /config hassio helpA brief description of your application

Usage:
  hassio [command]

Available Commands:
  addons        
  completion    Generates bash completion scripts
  hardware      
  hassos        
  help          Help about any command
  homeassistant homeassistant 
  host          
  info          
  snapshots     
  supervisor    

Flags:
      --api-token string   Hass.io API token
      --config string      config file (default is $HOME/.homeassistant.yaml)
      --endpoint string    Endpoint for Hass.io Supervisor ( default is 'hassio' )
  -h, --help               help for hassio
      --log-level string   Log level defaults to Warn
      --raw-json           Output raw JSON from the API

Use "hassio [command] --help" for more information about a command.

**Comment by WarmChocolateCake** [comment]
I'm running hass.io on a RasPi3...

> The Hass.io CLI is available in the SSH, SSH & Web Terminal, Visual Studio Code and IDE add-ons.

The SSH & Web Terminal addon doesn't appear to support the `hassio dns` command

Installing the SSH addon **does** appear to  support that command (not sure why they're different?)

**Comment by andreasfelder** [comment]
Yeah ESPHome devices broken and many other local devices. I guess my 2 cloud devices still work. Can we also enable manual updating of the supervisor. I hate automatic updates. No way to prep for anything that may break and no way to roll back.

**Comment by WarmChocolateCake** [comment]
IMHO, the general theme from most people here is:
1) Manual updates - or at least a big neon sign saying the supervisor has changed
2) Manual control. It appears that a lot of people control their DNS, so let's have a Web GUI place to configure these things.

**Comment by andreasfelder** [comment]
After doing hassio dns options --servers dns://IP_ADDRESS and rebooting the system it eventually started working again. (also when i say i rebooted i actually stopped the entire VM in Hyper-v) You can also double check after the reboot that the DNS server is correctly set by running hassio dns info

For me it took about 20 minutes to finally start working so maybe set it, reboot and grab some coffee.

**Comment by frenck** [comment]
If your `hassio` CLI does not have the `dns` subcommand, please update the add-ons. `dns` is obviously new.

Stop going offtopic, please. This discussion is confusinh enough for everybody already.

**Comment by mikemoyse** [comment]
> After doing hassio dns options --servers dns://IP_ADDRESS and rebooting the system it eventually started working again. (also when i say i rebooted i actually stopped the entire VM in Hyper-v) You can also double check after the reboot that the DNS server is correctly set by running hassio dns info
> 
> For me it took about 20 minutes to finally start working so maybe set it, reboot and grab some coffee.

I did that this morning, it worked for a while but after I came back from my daughter's horse riding lesson it was broken again.

**Comment by mihalski** [comment]
All I can say is that even though ti doesn't solve resolution from containers it DOES fix esphome devices if you follow the instructions to set the dns using the hassio cli and then restarting the host. 

For me that's a significant win and I can now wait for a more comprehensive solution.

**Comment by mikemoyse** [comment]
> All I can say is that even though it doesn't fix resolution from containers it DOES fix esphome devices if you follow the instructions to set the dns using the hassio cli and then restarting the host.

Doesn't work here, if I try to view the logs of an esphome device it can't find it as it's returning some weird public IP that's not even mine!

**Comment by alexyao2015** [comment]
Yeah the IP you're seeing is aws because it's using Google dns instead of local dns.

**Comment by mihalski** [comment]
If it couldn't find it it you wouldn't be seeing the logs.. Not sure what the weird public IP's it gets are but they're not the IP of the actual device.

For me it fixed it. Perhaps it takes a bit of time before it starts to work.

**Comment by mikemoyse** [comment]
I get: 
INFO Connecting to bledownstairs.XXXXX.house:6053 (52.216.106.82)

As Alex says, that's an Amazon IP, not the internal IP of my device. It's been like this all day, many restarts, many hours of leaving it alone, many attempts at telling it to use my internal DNS. I wish I could just rewind the supervisor, stop it from updating and get back to enjoying my weekend :-(

**Comment by alexyao2015** [comment]
> FYI for those running Hass.IO on Ubuntu:
> 
> `vi /usr/share/hassio/dns/corefile`
> 
> Change the DNS entries in there. Then do:
> 
> `docker restart hassio_dns`
> 
> And then restart HA from the UI. It should come back but will likely be overwritten if the container updates without this being corrected. Thanks to the instructions above for the pointer.

Try this.

**Comment by mikemoyse** [comment]
> 
> 
> > FYI for those running Hass.IO on Ubuntu:
> > `vi /usr/share/hassio/dns/corefile`
> > Change the DNS entries in there. Then do:
> > `docker restart hassio_dns`
> > And then restart HA from the UI. It should come back but will likely be overwritten if the container updates without this being corrected. Thanks to the instructions above for the pointer.
> 
> Try this.

The advice has been NOT to edit that file directly

**Comment by frenck** [comment]
I've locked further comments on this issue right now. A lot of comments have been made, solutions (workarounds) offered. We are aware and working on it. Thanks all for participating 👍

**Comment by frenck** [comment]
Re-opening.

ℹ️ **Supervisor 180 has been release**

This release addresses a couple of issues & comments:

- Google DNS has been replaced by the privacy-aware Quad9
- Random hostnames no longer resolve to AWS.
- `localhost` should now work, independent of add-on state.
- Custom DNS is now preferred correctly, CloudFlare & Quad9 are secondary
- Ability added to restart Hass.io DNS to apply settings

ℹ️ **All add-ons providing the `hassio` CLI have been updated with CLI v3.1.0**

This version of the CLI adds the `hassio dns restart` command, connecting to the restart endpoint added in Supervisor 180.

ℹ️ **Setting your own DNS server**

This requires both supervisor 180 and the latest add-ons with CLI v3.1.0

- `hassio dns options --servers dns://IP_ADDRESS`
- `hassio dns restart`

👍

**Comment by KiLLeRRaT** [comment]
@frenck, on behalf of us all, thank you very much for your efforts and quick response on this issue.

**Comment by hgregorian** [comment]
Initially received a 502 gateway error upon manual attempt to update supervisor via webUI.  Rebooted host for good measure and observed update occurred without further intervention.  Local name resolution working consistently and as expected since specified name servers are honored sequentially and not randomly.

Thanks for resolving this issue!

**Comment by LukasQ** [comment]
Thanks a bunch for your work!
in my case `hassio dns restart` displays only the help. No issue, as one can reboot the host - just saying.
An idea for the future: What do you think of automated service discovery like in AWS ECS?
https://aws.amazon.com/de/blogs/aws/amazon-ecs-service-discovery/

**Comment by frenck** [comment]
> in my case hassio dns restart displays only the help. No issue, as one can reboot the host - just saying.

Update the add-ons to the latest version providing CLI v3.1.0.

**Comment by LukasQ** [comment]
surprisingly the update check didn't find any till some minutes ago. Anyways, working. If you need help with any AWS stuff, e.g. Code Pipelines with automated testing, drop me a line.

**Comment by pvizeli** [comment]
A future change on that backend is, that we can read the host DNS settings over dbus from NetworkManager and add the local DNS as first server with fallback to others.

**Comment by davemuench** [comment]
Thanks for the update. Please consider not adding quad9 and cloudflare to the DNS list if we don't specify them. I understand local DNS is preferred, but after this issue I've blocked access on my firewall as my HA is as good as broken without access to my local DNS server.

**Comment by smoke007** [comment]
Thank you frenck for all your hard work to get this DNS issue resolved!

I wanted to give feedback on how my ESPHome integration DNS name resolution is still not working like it used to, to see if anyone else is having this same issue.

After updating to Supervisor 180 and updating all add-ons, ESPHome add-on will now connect to ESPHome devices and Show Logs will connect to devices again.  However, when going to HA, Configuration, Integrations, the ESPHome integrations still won't connect. I tried rebooting everything, including host system.

I found from SSH, I still couldn't ping the ESPHome devices by name. I added my local DNS server (home router) and restarted DNS via frenck's commands above.  I can now ping my device by name, ie: stair_lights and stair_lights.lan, but **not** stair_lights.local.  I see ESPHome add-on resolves device short names successfully by using device's name with .local at the end.

Existing devices under Integrations setup with ESPHome, still can't connect.  If I try to add an existing device using the short name, ie stair_lights, I get the error "Can't resolve address of the ESP. If this error persists, please set a static IP address".  However, both stair_lights.local and stair_lights.lan will resolve and device can be added.  All my devices were originally added successfully with the short name, hence the problem now.

So, currently, to fix all my ESPHome devices, I'd have to delete all the old devices and add them back using a FQDN name with .lan or .local.  (Tip, after deleting old devices, reboot Home Assistant before added devices with same name back otherwise duplicate name will be created and you'll have to manually clean it up within Entity Registry.)  Is this how ESPHome devices should be supported now within Integrations or is this part of the DNS bug that needs to be resolved yet?

Again, thank you for all your time and work you put in to Home Assistant!

**Comment by pvizeli** [comment]
`.local` is a special case and lookup anyway over multicast DNS aka mDNS. We never touch that with this change. I hope we can later integrate support for mDNS and allow to use multicast DNS from host network also inside virtual network like a bridge.

**Comment by mwild1** [comment]
Thanks for working on this issue. I am running supervisor 181 with 0.97.2 and my local devices are still unavailable (my Home Assistant log is full of name resolution errors).

Using ssh I can reproduce:

```
core-ssh:~# host living-room-tv
Host living-room-tv not found: 3(NXDOMAIN)
```

Manually directing the query to my router works:

```
core-ssh:~# host living-room-tv 192.168.178.1
Using domain server:
Name: 192.168.178.1
Address: 192.168.178.1#53
Aliases: 

living-room-tv has address 192.168.178.61
```

It appears that hassio is still using Google and Cloudflare for me:

```
core-ssh:~# hassio dns info
host: 172.30.32.3
latest_version: "1"
servers:
- dns://8.8.8.8
- dns://1.1.1.1
version: "1"
```

I have not modified any DNS configuration since everything broke, except for just supervisor and home assistant updates.

**Comment by LukasQ** [comment]
Well, as far as I can see you use a private resolver, so confugure it with: `hassio dns options --servers dns://192.168.178.1`

**Comment by bangadrum** [comment]
mwild 1 - try using a fully qualified domain name rather than just hostnames. Fixed most of mine by doing that.

**Comment by mikemoyse** [comment]
> mwild 1 - try using a fully qualified domain name rather than just hostnames. Fixed most of mine by doing that.

Shouldn't be necessary on a properly configured network. All my devices respond to hostname only from a command line apart from within HA.

**Comment by bangadrum** [comment]
I concur. Every other device on my network works fine with hostname alone. But putting the fqdn into my home assistant code fixed the dns issues I was having.

**Comment by agners** [comment]
> A future change on that backend is, that we can read the host DNS settings over dbus from NetworkManager and add the local DNS as first server with fallback to others.

@pvizeli did you consider parsing `/etc/resolv.conf`? As far as I know docker copies the hosts `resolv.conf` into the container. Parsing it would also work on systems not using NetworkManager.

In case there are better/more accurate information available from NetworkManager via D-Bus, then the code could still use D-Bus first with a fallback to `/etc/resolv.conf`.

Wrt DNS fallback to public DNS resovler: IMHO this should be optional still though. Especially for cloud-free HA installation public DNS resolvers are a bad fallback. Most external names (external to HassIO) my HA installation needs to resolve are local... I would prefer my system fails completely rather than works half way.

**Comment by Lymkin** [comment]
Why is the hassio-supervisor automatically upgraded?  I did not request the update to version 181, now my whole system is junk.  Half the pages don't work, system is now super slow.  Please ask before auto upgrading.  Once again....this is the kind of stuff that made me leave OpenHAB behind and now it seems HA is going to do that same types of things.

**Comment by etique57** [comment]
Meeting the same problems like everyone here (supervisor 181)
- Mysql addon not resolved
- local hostname (non fqdn) don't resolve

If I switch to my local dns server (using the option --servers), then:
- mysql addon still not resolved
- local hostname non-fqdn not resolved
- local hostname with fqdn do resolve

not sure how to retrieve the previous behaviour which worked fine.

**Comment by MattXcz** [comment]
:+1: 
Same here.
Fixed using 
`hassio dns options --servers dns://x.x.x.x`

**Comment by pssc** [comment]
I too had issues breaking my custom sensors, adding my own DNS via the cli tool and using the qualified local domain '.lan' in my case fixed the issues once hassos had been updated to allow for fixed order,I  needed to do update the .known_host file for ssh out access to allow for the new names also.

I would be great if we could have option to switch to update on admin demand for hassos as I too lost valuable time with the family and lost credits with the wife as a result of this one...

I have to pick my upgrade time usually when I have some spare capacity to deal with issues.

**Comment by etique57** [comment]
> 👍
> Same here.
> Fixed using
> `hassio dns options --servers dns://x.x.x.x`

Doesn't solve the non FQDN hostnames from my network nor the local resolution of Hassio MariaDB addon for me...

Any hint?

**Comment by pssc** [comment]
> > 👍
> > Same here.
> > Fixed using
> > `hassio dns options --servers dns://x.x.x.x`
> 
> Doesn't solve the non FQDN hostnames from my network nor the local resolution of Hassio MariaDB addon for me...
> 
> Any hint?

You have rebooted hassio or restarted the dns? and your are on Hypervisor >=181?
what is your local prefix?
have you tried from the ssh-addon >host xxx.yyy your_router_or_dns_ip

**Comment by Pelado-Mat** [comment]
I was hit with the same issue, been locked out off my own house.... I couldn't open the front gate (a simple esphome based relay).

@frenck and dev team, HASSIO is great, but please be more careful next time. This issue combined with the automatic update impacted us.

fixed using:
`hassio dns options --servers dns://my_local_dns_server`

**Comment by etique57** [comment]
> You have rebooted hassio or restarted the dns? and your are on Hypervisor >=181?
> what is your local prefix?
> hassio dns info returns?
> have you tried from the ssh-addon >host xxx.yyy your_router_or_dns_ip

Thanks for helping.

Yes I rebooted hassio multiple times, and I'm on Hypervisor 181.

```
~ hassio dns info
host: 172.30.32.3
latest_version: "1"
servers:
- dns://192.168.0.1
version: "1"
```

Now some tests:
```
~ host ampli
Host ampli.local.hass.io not found: 2(SERVFAIL)
~ host ampli.my.domain
ampli.my.domain has address 192.168.0.24
~ host ampli 192.168.0.1
Using domain server:
Name: 192.168.0.1
Address: 192.168.0.1#53
Aliases:

ampli.local.hass.io has address 172.30.32.1
~ host core-mariadb
core-mariadb.local.hass.io has adderss 172.30.33.0
Host core-mariadb.local.hass.io not found: 2(SERVFAIL)
```

I'm not quite able to make sense of what's wrong...

**Comment by hgregorian** [comment]
> > You have rebooted hassio or restarted the dns? and your are on Hypervisor >=181?
> > what is your local prefix?
> > hassio dns info returns?
> > have you tried from the ssh-addon >host xxx.yyy your_router_or_dns_ip
> 
> Thanks for helping.
> 
> Yes I rebooted hassio multiple times, and I'm on Hypervisor 181.
> 
> ```
> ~ hassio dns info
> host: 172.30.32.3
> latest_version: "1"
> servers:
> - dns://192.168.0.1
> version: "1"
> ```
> 
> Now some tests:
> 
> ```
> ~ host ampli
> Host ampli.local.hass.io not found: 2(SERVFAIL)
> ~ host ampli.my.domain
> ampli.my.domain has address 192.168.0.24
> ~ host ampli 192.168.0.1
> Using domain server:
> Name: 192.168.0.1
> Address: 192.168.0.1#53
> Aliases:
> 
> ampli.local.hass.io has address 172.30.32.1
> ~ host core-mariadb
> core-mariadb.local.hass.io has adderss 172.30.33.0
> Host core-mariadb.local.hass.io not found: 2(SERVFAIL)
> ```
> 
> I'm not quite able to make sense of what's wrong...

The only search domain ('search' in /etc/resolv.conf) defined is `local.hass.io`.  If the host you're trying to reach is in a different domain, then specifying the FQDN is needed.  I'm not certain if this has always been practice (as far as the resolver setup in home-assistant is concerned), but I use FQDNs in practice and not PQDN or simple hostnames, therefore I would not have noticed an issue (in my setup).  This issue seems only peripherally connected to what caused this issue's creation to begin with.

It is curious however that manually adding another domain to `/etc/resolv.conf` still results in `Host hostname.local.hass.io not found: 2(SERVFAIL)` and doesn't seem to be traversing the list of search domains.

**Comment by etique57** [comment]
> The only search domain ('search' in /etc/resolv.conf) defined is `local.hass.io`. If the host you're trying to reach is in a different domain, then specifying the FQDN is needed. I'm not certain if this has always been practice (as far as the resolver setup in home-assistant is concerned), but I use FQDNs in practice and not PQDN or simple hostnames, therefore I would not have noticed an issue (in my setup). This issue seems only peripherally connected to what caused this issue's creation to begin with.
> 
> It is curious however that manually adding another domain to `/etc/resolv.conf` still results in `Host hostname.local.hass.io not found: 2(SERVFAIL)` and doesn't seem to be traversing the list of search domains.

Ok, I didn't know I needed to modify `/etc/resolv.conf`. But all these informations are properly setup in my dhcp server. Not sure why it's not taken in account as it used to be.

It has been a very long time I had to configure anything regarding DNS resolutions...

**Comment by Landrash** [comment]
One problem that I've found is that integrations that really on discovery seems to be dead for me currently. I'm assuming this is DNS related.

**Comment by Landrash** [comment]
@pvizeli Strange. Was this broken with this "chain" or updates?

Since I moved my installation to hass.io I didn't have anything hard coded
and only tried to use the auto-discovery part done with the onboarding.

If this is the case then it's a rather large regression.

**Comment by etique57** [comment]
hello @pvizeli , how can I reset the dns conf to the HassOs default? (I added my own DNS server).

Thanks!

**Comment by lightbody** [comment]
I'm running hassio as described in [this article](https://www.smarthomebeginner.com/install-hass-io-on-docker-linux/). The result is that my Ubuntu host doesn't have a `hassio` command at all. So I'm not entirely sure where I'm supposed to go to run `hassio dns options...` to fix this. I'm guessing it's something I run in the container named `hassio_supervisor`, but when I exec'd into I didn't see a `hassio` command either. I did, however, see that the ENTRYPOINT for the container is running `python3 -m hassio`, so maybe I'm getting close?

**Comment by richard-scott** [comment]
@lightbody SSH to your Ubuntu Host and try this as root:

```
for ID in $(docker ps -q) ; do
  if docker exec -it ${ID} $SHELL -c "which hassio" ; then
    docker exec -it ${ID} $SHELL
    break
  fi
done
```
You'll then be connected to the Docker container with that command.

You can then update DNS with this:
```
hassio dns options --servers dns://IP_ADDRESS
```

**Comment by deftdawg** [comment]
By default my ``homeassitant`` container (homeassistant/qemux86-64-homeassistant:0.98.2) has the following /etc/resolv.conf:
``
search local.hass.io
nameserver 172.30.32.3
``

To fix local name resolution, I'm using: 
```
 docker exec -it homeassistant bash -c 'echo "options ndots:0" >> /etc/resolv.conf'
```
each time the container is started.

How can get hassio to generate /etc/resolv.conf with the correct ndots option by default?

**Comment by lightbody** [comment]
@richard-scott That doesn't work. What I was trying to say in my previous comment was that none of the three hass/ha related containers contain the command "hassio". The cloest thing I've found is that the hassio_supervisor container has a python3 process running a module called "hassio", but I don't know if that is the same thing or how to use it.

**Comment by deftdawg** [comment]
@lightbody I found a copy of hassio inside a VSCode container (hassioaddons/vscode-amd64:0.6.5), though it didn't help as there doesn't seem to be a way to append ndots or remove search from the dns options...

**Comment by crowbarz** [comment]
@lightbody https://github.com/home-assistant/hassio-cli is the hassio CLI that you are looking for. You will also probably need to set the endpoint and create an API token per the README: I haven't figured out how to extract a usable token from the hass.io container to use to run the CLI, nor how the other addons that include the hassio CLI magically get a usable token to talk to the API.

**Comment by deftdawg** [comment]
@crowbarz cli won't help...  there's no api to control dns search space defined in the api (see https://github.com/home-assistant/hassio/blob/dev/API.md#DNS)

**Comment by lightbody** [comment]
Just a follow up on this (@deftdawg @crowbarz) -- I ended up activating the SSH plugin and then SSH'ing in and that had the "hassio" command. 🤷‍♂ I also had to set the port to 8122 because 22 was taken by my host OS that is running the docker containers.

**Comment by AlexStankov** [comment]
Hi all,
I have installed hassio on ubuntu server and have the same issue - homeassistant container cannot resolve names from my local network. There was no hassio command in none of docker containers. As was mentioned above - I installed the ssh addon and executed command "hassio dns options --servers dns://192.168.1.1" in terminal of home assistant web ui. This didn't help. This works for container "addon_core_ssh", but don't work for container "homeassistant".
What may be wrong in my case? How can I add the proper dns path to the hassio dns daemon?

**Comment by AlexStankov** [comment]
Hm... It may be resolved in ".lan" domain. For example, device.lan. But my network works without domain. So device should be resolved as "device". The problem may be solved by adding line "options ndots:0" to the file /etc/resolv.conf in homeassistant container. But after hassio restart it is rewritten.
How could this problem be solved?

**Comment by FaserF** [comment]
Issue still persists for me.
hassio dns options --servers dns://192.168.178.1
Done that, restarted dns with "hassio dns restart"

This is my "hassio dns info":
```
~ $ hassio dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.178.2
- dns://fd00::9a9b:cbff:fea5:206d
servers:
- dns://192.168.178.1
version: "1"
```

I have completedly blocked all google dns server on my network and I am using pihole (which is running on 192.168.178.2
Is there a way to force using my router or 1.1.1.1 ?

This is the log i get in hassio:
```
20-01-23 12:09:47 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/sabeechen/hassio-google-drive-backup repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/sabeechen/hassio-google-drive-backup/': Could not resolve host: github.com'.
20-01-23 12:09:47 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/home-assistant/hassio-addons/': Could not resolve host: github.com'.
20-01-23 12:09:47 ERROR (MainThread) [hassio.store.git] Can't update https://github.com/hassio-addons/repository repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: unable to access 'https://github.com/hassio-addons/repository/': Could not resolve host: github.com'.
```

**Comment by galapogos01** [comment]
This is poor behaviour. hassio should honour the DHCP delivered DNS server.

**Comment by jschwalbe** [comment]
I too am running on Ubuntu, and having similar problems.

I've been asking in discord, on the forum and on reddit, and I cannot find a simple answer. **How to I install Home Assistant in such a way that I can use the 'hassio' command as everyone else seems to be able to do (without the convoluted docker incantation)**? Is there a "recommended" installation method? This Ubuntu + docker stuff doesn't seem to be working for many people, myself included..  (sorry/not sorry for (ab)using the issue for this question).

**Comment by AlexStankov** [comment]
I fixed my issue by adding the following automation:
```
- id: '1578321747819'
  alias: Patch resolv.conf on startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: shell_command.patch_resolv_conf
```
and by adding the following code to configuration.yaml:
```
shell_command:
  patch_resolv_conf: 'echo "options ndots:0" >> /etc/resolv.conf'
```

**Comment by pharpe** [comment]
I'm having this same issue.  I see the thread is closed but I don't see a resolution.  I've tried a few of the suggestions and having no luck.

**Comment by richard-scott** [comment]
@jschwalbe Have you looked at [this ](https://github.com/home-assistant/cli#install) regarding the installation of the 'hassio' binary?
Or you can run my [code ](https://github.com/home-assistant/supervisor/issues/1231#issuecomment-527040856) to dynamically locate the instance to save setting up tokens etc.

**Comment by pharpe** [comment]
> @jschwalbe Have you looked at [this ](https://github.com/home-assistant/cli#install) regarding the installation of the 'hassio' binary?
> Or you can run my [code ](https://github.com/home-assistant/supervisor/issues/1231#issuecomment-527040856) to dynamically locate the instance to save setting up tokens etc.

I installed the hassio-cli per the go get command in the lined guide.  It appears to install without error but I still get 
`ha: command not found`

When I run the shell script in you second link I get this:

`failed to resize tty, using default size
                                        OCI runtime exec failed: exec failed: co               ntainer_linux.go:349: starting container process caused "exec: \"/bin/bash\": st               at /bin/bash: no such file or directory": unknown
`

**Comment by jschwalbe** [comment]
> Or you can run my [code ](https://github.com/home-assistant/supervisor/issues/1231#issuecomment-527040856) to dynamically locate the instance to save setting up tokens etc.

@richard-scott Thanks! This worked for getting me into the shell (but it does not have the ha command).  When I try to ping a local address such as `ping makar.local` (my laptop) or `ping makar`, neither work, `Name or service not known`.

When I try the same from core_ssh it fails similarly. 
`ha dns info` shows:
`host: 172.30.32.3
latest_version: "1"
locals:
- dns://192.168.25.81
servers:
- dns://192.168.25.81
version: "1"`

**Comment by richard-scott** [comment]
@jschwalbe look for the old name 'hassio'

**Comment by jschwalbe** [comment]
@richard-scott ok that worked (odd). but still having the same inability to ping or lookup any of my `.local` domains. :(
Any thoughts?

**Comment by agners** [comment]
@jschwalbe do you use `.local` as default suffix for your local DNS server? If so, I think it could be because `.local` is also used by mDNS, and could be handled a bit special by the new NDS handling of HA.

**Comment by jschwalbe** [comment]
@agners yes, my entire network has always used .local for the domains. 

But that doesn’t explain why it resolves poop.com with a DNS server other than the one I specify at the router. Right?

**Comment by sanderlv** [comment]
I read the entire thread. i run hassos as the virtual appliance mode. how to "solve" this? What do i need to do to get my own local DNS server activated?

**Comment by richard-scott** [comment]
On my setup I have a VirtualBox VM running Ubuntu that is also running Docker, running HA.

I installed my setup following the Alternative method detailed here:
https://www.home-assistant.io/hassio/installation/#alternative-install-home-assistant-supervised-on-a-generic-linux-host

I have also added DHCP Option 119 to my DHCP server to push out a search domain. In my case its home.lan.

Now I can ping just the hostname etc.

**Comment by kerozen54** [comment]
hi all. just finished to install hass.io 0.107.0on a fresh new rpi4.
first run successfully.
then i set a static ip and gateway and dns
now, homeassistant can not access internet anymore.
tried to use the terminal addon to set the dns:
ha dns update --servers dns://172.16.1.1
then
ha dns info
host: 172.30.32.3
latest_version: "1"
locals:
- dns://172.16.1.1
- dns://8.8.8.8
- dns://2a01:cb11:3ef:fb00:924d:4aff:fee7:87f0
- dns://fe80::924d:4aff:fee7:87f0
servers:
- dns://172.16.1.1
version: "1"

already rebooted hassio_dns and restarted homeassistant, without better results.

all was working when using dhcp.
Any more clue ?

**Comment by WarmChocolateCake** [comment]
Probably better to put this on the forum rather than a closed github issue - you will have more response.

Maybe return to DHCP and check it is still working.

**Comment by bitmerchandise** [comment]
I fixed it by going to /usr/share/hassio and editing the dns.json file. I put my local dns first on the list. The only issue I still have is that if I only specify the hostname then it appends  local.hassio.io

`
{
  "servers": [
    "dns://192.168.1.43",
    "dns://8.8.8.8"
  ],
  "version": "9",
  "image": "homeassistant/amd64-hassio-dns"
}
`

Esphome brought me down this path when I added my first device and I had to use IP address instead of name

This seems to work after reboot... at least after 1 reboot

This was done on Ubuntu 19.10
